# Generated by Django 5.0.6 on 2024-05-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sender",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("sender", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("comment", models.CharField(max_length=200)),
                ("is_active", models.BooleanField()),
                ("prefix", models.IntegerField()),
                ("total_sms_count", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("channel_login", models.CharField(max_length=10)),
                ("channel_password", models.CharField(max_length=10)),
                ("run_count", models.IntegerField()),
                (
                    "sender",
                    models.ManyToManyField(related_name="senders", to="sms.sender"),
                ),
                ("text", models.ManyToManyField(related_name="texts", to="sms.text")),
            ],
        ),
    ]
