# Generated by Django 5.0.6 on 2024-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_alter_broadcast_id_alter_sender_id_alter_text_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="run_count",
            field=models.IntegerField(default=0),
        ),
    ]
