# Generated by Django 5.0.6 on 2024-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0003_alter_broadcast_run_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="sent_sms",
            field=models.IntegerField(default=0),
        ),
    ]
