# Generated by Django 5.0.6 on 2024-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0005_broadcast_phone_number_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="text",
            field=models.CharField(max_length=145, unique=True),
        ),
    ]
