# Generated by Django 5.0.6 on 2024-07-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_alter_text_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="broadcast",
            name="prefix",
        ),
        migrations.CreateModel(
            name="Prefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.IntegerField()),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefix",
                        to="sms.broadcast",
                    ),
                ),
            ],
        ),
    ]
