# Generated by Django 5.0.6 on 2024-07-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0008_alter_prefix_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="comment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
